name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: 
      name: test

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./azure-voting-app-redis/azure-voting-app-redis/azure-vote/ --file Dockerfile --tag my-image-name:$(date +%s)
